// <auto-generated />
using System;
using DerasaX.Infrastructure.DbHelper.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DerasaX.Infrastructure.Migrations
{
    [DbContext(typeof(DerasaXDbContext))]
    [Migration("20260126013635_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DerasaX.Domain.Entities.Base.BaseEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BaseEntity");

                    b.HasDiscriminator().HasValue("BaseEntity");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DerasaX.Domain.Entities.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("TenantId");

                    b.ToTable("AspNetUsers", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("DerasaX.Domain.Entities.Models.Tenant", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("ConnectionString")
                        .HasColumnType("text");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("SubscriptionPlan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("tenants");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DerasaX.Domain.Entities.Models.Announcement", b =>
                {
                    b.HasBaseType("DerasaX.Domain.Entities.Base.BaseEntity");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("TargetAudience")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Announcement");
                });

            modelBuilder.Entity("DerasaX.Domain.Entities.Models.Grade", b =>
                {
                    b.HasBaseType("DerasaX.Domain.Entities.Base.BaseEntity");

                    b.Property<string>("gradeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Grade");
                });

            modelBuilder.Entity("DerasaX.Domain.Entities.Models.GradeSubject", b =>
                {
                    b.HasBaseType("DerasaX.Domain.Entities.Base.BaseEntity");

                    b.Property<string>("GradeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("GradeId");

                    b.HasIndex("SubjectId");

                    b.HasDiscriminator().HasValue("GradeSubject");
                });

            modelBuilder.Entity("DerasaX.Domain.Entities.Models.Lesson", b =>
                {
                    b.HasBaseType("DerasaX.Domain.Entities.Base.BaseEntity");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UnitId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("UnitId");

                    b.ToTable("BaseEntity", t =>
                        {
                            t.Property("Title")
                                .HasColumnName("Lesson_Title");
                        });

                    b.HasDiscriminator().HasValue("Lesson");
                });

            modelBuilder.Entity("DerasaX.Domain.Entities.Models.LessonMaterial", b =>
                {
                    b.HasBaseType("DerasaX.Domain.Entities.Base.BaseEntity");

                    b.Property<string>("LessonId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("LessonId");

                    b.ToTable("BaseEntity", t =>
                        {
                            t.Property("Title")
                                .HasColumnName("LessonMaterial_Title");
                        });

                    b.HasDiscriminator().HasValue("LessonMaterial");
                });

            modelBuilder.Entity("DerasaX.Domain.Entities.Models.Notification", b =>
                {
                    b.HasBaseType("DerasaX.Domain.Entities.Base.BaseEntity");

                    b.Property<string>("ActionUrl")
                        .HasColumnType("text");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<int?>("TargetAudience")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("notificationCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("UserId");

                    b.ToTable("BaseEntity", t =>
                        {
                            t.Property("Body")
                                .HasColumnName("Notification_Body");

                            t.Property("TargetAudience")
                                .HasColumnName("Notification_TargetAudience");

                            t.Property("Title")
                                .HasColumnName("Notification_Title");
                        });

                    b.HasDiscriminator().HasValue("Notification");
                });

            modelBuilder.Entity("DerasaX.Domain.Entities.Models.Post", b =>
                {
                    b.HasBaseType("DerasaX.Domain.Entities.Base.BaseEntity");

                    b.Property<int>("CommentsCount")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LikesCount")
                        .HasColumnType("integer");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ViewsCount")
                        .HasColumnType("integer");

                    b.HasIndex("UserId");

                    b.ToTable("BaseEntity", t =>
                        {
                            t.Property("Content")
                                .HasColumnName("Post_Content");

                            t.Property("CreatedAt")
                                .HasColumnName("Post_CreatedAt");

                            t.Property("UserId")
                                .HasColumnName("Post_UserId");
                        });

                    b.HasDiscriminator().HasValue("Post");
                });

            modelBuilder.Entity("DerasaX.Domain.Entities.Models.Question", b =>
                {
                    b.HasBaseType("DerasaX.Domain.Entities.Base.BaseEntity");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<string>("QuizId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("QuizId");

                    b.ToTable("BaseEntity", t =>
                        {
                            t.Property("Type")
                                .HasColumnName("Question_Type");
                        });

                    b.HasDiscriminator().HasValue("Question");
                });

            modelBuilder.Entity("DerasaX.Domain.Entities.Models.QuestionOption", b =>
                {
                    b.HasBaseType("DerasaX.Domain.Entities.Base.BaseEntity");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<string>("QuestionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("QuestionId");

                    b.ToTable("BaseEntity", t =>
                        {
                            t.Property("Text")
                                .HasColumnName("QuestionOption_Text");
                        });

                    b.HasDiscriminator().HasValue("QuestionOption");
                });

            modelBuilder.Entity("DerasaX.Domain.Entities.Models.Quiz", b =>
                {
                    b.HasBaseType("DerasaX.Domain.Entities.Base.BaseEntity");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LessonId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TimeLimitMinutes")
                        .HasColumnType("integer");

                    b.HasIndex("LessonId");

                    b.ToTable("BaseEntity", t =>
                        {
                            t.Property("LessonId")
                                .HasColumnName("Quiz_LessonId");
                        });

                    b.HasDiscriminator().HasValue("Quiz");
                });

            modelBuilder.Entity("DerasaX.Domain.Entities.Models.QuizGeneration", b =>
                {
                    b.HasBaseType("DerasaX.Domain.Entities.Base.BaseEntity");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PromptUsed")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QuizId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("QuizId");

                    b.ToTable("BaseEntity", t =>
                        {
                            t.Property("QuizId")
                                .HasColumnName("QuizGeneration_QuizId");
                        });

                    b.HasDiscriminator().HasValue("QuizGeneration");
                });

            modelBuilder.Entity("DerasaX.Domain.Entities.Models.QuizSubmission", b =>
                {
                    b.HasBaseType("DerasaX.Domain.Entities.Base.BaseEntity");

                    b.Property<int>("AchievedScore")
                        .HasColumnType("integer");

                    b.Property<string>("QuizId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TeacherFeedback")
                        .HasColumnType("text");

                    b.Property<int>("TotalScore")
                        .HasColumnType("integer");

                    b.Property<string>("submissionStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("QuizId");

                    b.HasIndex("StudentId");

                    b.ToTable("BaseEntity", t =>
                        {
                            t.Property("QuizId")
                                .HasColumnName("QuizSubmission_QuizId");
                        });

                    b.HasDiscriminator().HasValue("QuizSubmission");
                });

            modelBuilder.Entity("DerasaX.Domain.Entities.Models.StudentInsight", b =>
                {
                    b.HasBaseType("DerasaX.Domain.Entities.Base.BaseEntity");

                    b.Property<double>("ConfidenceScore")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Performance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("StudentId");

                    b.ToTable("BaseEntity", t =>
                        {
                            t.Property("GeneratedAt")
                                .HasColumnName("StudentInsight_GeneratedAt");

                            t.Property("StudentId")
                                .HasColumnName("StudentInsight_StudentId");
                        });

                    b.HasDiscriminator().HasValue("StudentInsight");
                });

            modelBuilder.Entity("DerasaX.Domain.Entities.Models.StudentLessonProgress", b =>
                {
                    b.HasBaseType("DerasaX.Domain.Entities.Base.BaseEntity");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LessonId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("LessonId");

                    b.HasIndex("StudentId");

                    b.ToTable("BaseEntity", t =>
                        {
                            t.Property("LessonId")
                                .HasColumnName("StudentLessonProgress_LessonId");

                            t.Property("StudentId")
                                .HasColumnName("StudentLessonProgress_StudentId");
                        });

                    b.HasDiscriminator().HasValue("StudentLessonProgress");
                });

            modelBuilder.Entity("DerasaX.Domain.Entities.Models.Subject", b =>
                {
                    b.HasBaseType("DerasaX.Domain.Entities.Base.BaseEntity");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Subject");
                });

            modelBuilder.Entity("DerasaX.Domain.Entities.Models.SubmissionAnswer", b =>
                {
                    b.HasBaseType("DerasaX.Domain.Entities.Base.BaseEntity");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<int>("PointsEarned")
                        .HasColumnType("integer");

                    b.Property<string>("QuestionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QuizSubmissionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SelectedOptionId")
                        .HasColumnType("text");

                    b.HasIndex("QuestionId");

                    b.HasIndex("QuizSubmissionId");

                    b.HasIndex("SelectedOptionId");

                    b.ToTable("BaseEntity", t =>
                        {
                            t.Property("IsCorrect")
                                .HasColumnName("SubmissionAnswer_IsCorrect");

                            t.Property("QuestionId")
                                .HasColumnName("SubmissionAnswer_QuestionId");
                        });

                    b.HasDiscriminator().HasValue("SubmissionAnswer");
                });

            modelBuilder.Entity("DerasaX.Domain.Entities.Models.SupportRequest", b =>
                {
                    b.HasBaseType("DerasaX.Domain.Entities.Base.BaseEntity");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResponseMessage")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("UserId");

                    b.ToTable("BaseEntity", t =>
                        {
                            t.Property("CreatedAt")
                                .HasColumnName("SupportRequest_CreatedAt");

                            t.Property("Type")
                                .HasColumnName("SupportRequest_Type");

                            t.Property("UserId")
                                .HasColumnName("SupportRequest_UserId");
                        });

                    b.HasDiscriminator().HasValue("SupportRequest");
                });

            modelBuilder.Entity("DerasaX.Domain.Entities.Models.Unit", b =>
                {
                    b.HasBaseType("DerasaX.Domain.Entities.Base.BaseEntity");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("SubjectId");

                    b.ToTable("BaseEntity", t =>
                        {
                            t.Property("SubjectId")
                                .HasColumnName("Unit_SubjectId");

                            t.Property("Title")
                                .HasColumnName("Unit_Title");
                        });

                    b.HasDiscriminator().HasValue("Unit");
                });

            modelBuilder.Entity("DerasaX.Domain.Entities.Models.Parent", b =>
                {
                    b.HasBaseType("DerasaX.Domain.Entities.Models.ApplicationUser");

                    b.ToTable("Parent", (string)null);
                });

            modelBuilder.Entity("DerasaX.Domain.Entities.Models.SchoolAdmin", b =>
                {
                    b.HasBaseType("DerasaX.Domain.Entities.Models.ApplicationUser");

                    b.ToTable("SchoolAdmin", (string)null);
                });

            modelBuilder.Entity("DerasaX.Domain.Entities.Models.Student", b =>
                {
                    b.HasBaseType("DerasaX.Domain.Entities.Models.ApplicationUser");

                    b.Property<string>("GradeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("GradeId");

                    b.ToTable("Student", (string)null);
                });

            modelBuilder.Entity("DerasaX.Domain.Entities.Models.SystemAdmin", b =>
                {
                    b.HasBaseType("DerasaX.Domain.Entities.Models.ApplicationUser");

                    b.ToTable("SystemAdmin", (string)null);
                });

            modelBuilder.Entity("DerasaX.Domain.Entities.Models.Teacher", b =>
                {
                    b.HasBaseType("DerasaX.Domain.Entities.Models.ApplicationUser");

                    b.ToTable("Teacher", (string)null);
                });

            modelBuilder.Entity("DerasaX.Domain.Entities.Models.ApplicationUser", b =>
                {
                    b.HasOne("DerasaX.Domain.Entities.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DerasaX.Domain.Entities.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DerasaX.Domain.Entities.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DerasaX.Domain.Entities.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DerasaX.Domain.Entities.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DerasaX.Domain.Entities.Models.GradeSubject", b =>
                {
                    b.HasOne("DerasaX.Domain.Entities.Models.Grade", "Grade")
                        .WithMany("GradeSubjects")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DerasaX.Domain.Entities.Models.Subject", "Subject")
                        .WithMany("GradeSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grade");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("DerasaX.Domain.Entities.Models.Lesson", b =>
                {
                    b.HasOne("DerasaX.Domain.Entities.Models.Unit", "Unit")
                        .WithMany("Lessons")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("DerasaX.Domain.Entities.Models.LessonMaterial", b =>
                {
                    b.HasOne("DerasaX.Domain.Entities.Models.Lesson", "Lesson")
                        .WithMany("materials")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("DerasaX.Domain.Entities.Models.Notification", b =>
                {
                    b.HasOne("DerasaX.Domain.Entities.Models.ApplicationUser", "User")
                        .WithMany("notifications")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DerasaX.Domain.Entities.Models.Post", b =>
                {
                    b.HasOne("DerasaX.Domain.Entities.Models.ApplicationUser", "User")
                        .WithMany("posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DerasaX.Domain.Entities.Models.Question", b =>
                {
                    b.HasOne("DerasaX.Domain.Entities.Models.Quiz", "Quiz")
                        .WithMany("Questions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("DerasaX.Domain.Entities.Models.QuestionOption", b =>
                {
                    b.HasOne("DerasaX.Domain.Entities.Models.Question", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("DerasaX.Domain.Entities.Models.Quiz", b =>
                {
                    b.HasOne("DerasaX.Domain.Entities.Models.Lesson", "Lesson")
                        .WithMany("Quizzes")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("DerasaX.Domain.Entities.Models.QuizGeneration", b =>
                {
                    b.HasOne("DerasaX.Domain.Entities.Models.Quiz", "Quiz")
                        .WithMany()
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("DerasaX.Domain.Entities.Models.QuizSubmission", b =>
                {
                    b.HasOne("DerasaX.Domain.Entities.Models.Quiz", "Quiz")
                        .WithMany("QuizSubmissions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DerasaX.Domain.Entities.Models.Student", "Student")
                        .WithMany("quizSubmissions")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("DerasaX.Domain.Entities.Models.StudentInsight", b =>
                {
                    b.HasOne("DerasaX.Domain.Entities.Models.Student", "Student")
                        .WithMany("studentInsights")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("DerasaX.Domain.Entities.Models.StudentLessonProgress", b =>
                {
                    b.HasOne("DerasaX.Domain.Entities.Models.Lesson", "Lesson")
                        .WithMany("studentLessonProgresses")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DerasaX.Domain.Entities.Models.Student", "Student")
                        .WithMany("studentLessonProgresses")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("DerasaX.Domain.Entities.Models.SubmissionAnswer", b =>
                {
                    b.HasOne("DerasaX.Domain.Entities.Models.Question", "Question")
                        .WithMany("SubmissionAnswers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DerasaX.Domain.Entities.Models.QuizSubmission", "QuizSubmission")
                        .WithMany("SubmissionAnswers")
                        .HasForeignKey("QuizSubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DerasaX.Domain.Entities.Models.QuestionOption", "SelectedOption")
                        .WithMany("SubmissionAnswers")
                        .HasForeignKey("SelectedOptionId");

                    b.Navigation("Question");

                    b.Navigation("QuizSubmission");

                    b.Navigation("SelectedOption");
                });

            modelBuilder.Entity("DerasaX.Domain.Entities.Models.SupportRequest", b =>
                {
                    b.HasOne("DerasaX.Domain.Entities.Models.ApplicationUser", "User")
                        .WithMany("supportRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DerasaX.Domain.Entities.Models.Unit", b =>
                {
                    b.HasOne("DerasaX.Domain.Entities.Models.Subject", "Subject")
                        .WithMany("Units")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("DerasaX.Domain.Entities.Models.Parent", b =>
                {
                    b.HasOne("DerasaX.Domain.Entities.Models.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("DerasaX.Domain.Entities.Models.Parent", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DerasaX.Domain.Entities.Models.SchoolAdmin", b =>
                {
                    b.HasOne("DerasaX.Domain.Entities.Models.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("DerasaX.Domain.Entities.Models.SchoolAdmin", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DerasaX.Domain.Entities.Models.Student", b =>
                {
                    b.HasOne("DerasaX.Domain.Entities.Models.Grade", "Grade")
                        .WithMany("students")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DerasaX.Domain.Entities.Models.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("DerasaX.Domain.Entities.Models.Student", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grade");
                });

            modelBuilder.Entity("DerasaX.Domain.Entities.Models.SystemAdmin", b =>
                {
                    b.HasOne("DerasaX.Domain.Entities.Models.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("DerasaX.Domain.Entities.Models.SystemAdmin", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DerasaX.Domain.Entities.Models.Teacher", b =>
                {
                    b.HasOne("DerasaX.Domain.Entities.Models.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("DerasaX.Domain.Entities.Models.Teacher", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DerasaX.Domain.Entities.Models.ApplicationUser", b =>
                {
                    b.Navigation("notifications");

                    b.Navigation("posts");

                    b.Navigation("supportRequests");
                });

            modelBuilder.Entity("DerasaX.Domain.Entities.Models.Grade", b =>
                {
                    b.Navigation("GradeSubjects");

                    b.Navigation("students");
                });

            modelBuilder.Entity("DerasaX.Domain.Entities.Models.Lesson", b =>
                {
                    b.Navigation("Quizzes");

                    b.Navigation("materials");

                    b.Navigation("studentLessonProgresses");
                });

            modelBuilder.Entity("DerasaX.Domain.Entities.Models.Question", b =>
                {
                    b.Navigation("Options");

                    b.Navigation("SubmissionAnswers");
                });

            modelBuilder.Entity("DerasaX.Domain.Entities.Models.QuestionOption", b =>
                {
                    b.Navigation("SubmissionAnswers");
                });

            modelBuilder.Entity("DerasaX.Domain.Entities.Models.Quiz", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("QuizSubmissions");
                });

            modelBuilder.Entity("DerasaX.Domain.Entities.Models.QuizSubmission", b =>
                {
                    b.Navigation("SubmissionAnswers");
                });

            modelBuilder.Entity("DerasaX.Domain.Entities.Models.Subject", b =>
                {
                    b.Navigation("GradeSubjects");

                    b.Navigation("Units");
                });

            modelBuilder.Entity("DerasaX.Domain.Entities.Models.Unit", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("DerasaX.Domain.Entities.Models.Student", b =>
                {
                    b.Navigation("quizSubmissions");

                    b.Navigation("studentInsights");

                    b.Navigation("studentLessonProgresses");
                });
#pragma warning restore 612, 618
        }
    }
}
